module.exports = {
  PLEASE_FILL_FIRM: 'Please fill out this form',
  PLEASE_GET_THIS_PREREQUISITE_PRODUCT: 'Looks like you\'ll need to get one of these first...somewhere else',
  TELL_ME_MORE: 'tell me more about this "{0}," it sounds interesting',
  NO_COMPRENDO: 'Huh? What\'s a "{0}"? I only understand simple messages. One day, when I\'m a real boy...',
  // HOT_NAME: '{0}, eh? Hot name!',
  GOT_PRODUCT: 'Yes! You got a {0}. You know, we don\'t give those out to just anybody',
  APPLICATION_NOT_FOUND: 'Hm, application not found. Please re-apply, but be happy about it!',
  SORRY_TO_FORGET_YOU: 'You\'re pretty unforgettable, but alright',
  // NICE_TO_MEET_YOU: 'Nice to meet you!',
  HI_JOE: 'Hi {0}!',
  IM_HERE_IF_YOU_NEED: 'I\'m here if you need me',
  ANOTHER: 'Another {0}? Whooah!!',
  PRODUCT_LIST_MESSAGE: 'See a list of products',
  PRODUCT_APPLICATION: 'Product Application',
  AGE_VERIFICATION: 'Age Verification',
}
