
module.exports = {
  SUBMITTED: 'tradle.ApplicationSubmitted',
  DENIAL: 'tradle.ApplicationDenial',
  APPROVAL: 'tradle.ApplicationApproval',
  APPLICATION: 'tradle.Application',
  VERIFICATION: 'tradle.Verification',
  FORGOT_YOU: 'tradle.ForgotYou',
  FORGET_ME: 'tradle.ForgetMe',
  FORM_REQUEST: 'tradle.FormRequest',
  NEXT_FORM_REQUEST: 'tradle.NextFormRequest',
  PRODUCT_REQUEST: 'tradle.ProductRequest',
  REMEDIATION: 'tradle.Remediation',
  CONFIRMATION: 'tradle.Confirmation',
  PRODUCT_APPLICATION: 'tradle.ProductApplication',
  IDENTITY_PUBLISH_REQUEST: 'tradle.IdentityPublishRequest',
  SIMPLE_MESSAGE: 'tradle.SimpleMessage',
  FORM: 'tradle.Form',
  VERIFIED_ITEM: 'tradle.VerifiedItem',
  CONFIRM_PACKAGE_REQUEST: 'tradle.VerifiedItem',
  MY_PRODUCT: 'tradle.MyProduct',
  MODELS_PACK: 'tradle.ModelsPack',
  SELF_INTRODUCTION: 'tradle.SelfIntroduction',
  IDENTITY: 'tradle.Identity',
  APPLICATION_STUB: 'tradle.products.ApplicationStub',
  ROLE: 'tradle.products.Role',
  CUSTOMER: 'tradle.products.Customer',
  TS_AND_CS_STATE: 'tradle.products.TsAndCsState',
  SUBMISSION: 'tradle.ApplicationSubmission',
}
